### PR TITLE
Local numpy embedders

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Description of changes
Local embedder which is Numpy based - Squeezenet

#### Discusion

- Speed: Tensorflow: ~0.025 per image, Numpy: ~0.17 per image. The speed difference between Numpy and Tensorflow is big (the order of 10).
- Should Numpy deep library be a separate package or included in image analytics. Currently, it is separate since it is quite big and complex. 

##### Includes
- [X] Code changes
- [X] Tests
- [X] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
Before the implementation is finished I think we need to discuss. The main issue here is that Numpy implementation of embedding is much slower than one by Tensorflow (Tensorflow is highly optimized on some types of processor instructions). Tensorflow, for example, needs ~0.025 s per image while Numpy implementation needs ~0.17 s per images what is the difference of almost order 10. What should we do here? Do we go back to some deep learning library (like Tensorflow) or we stay with slower Numpy based embedding? @markotoplak @lanzagar

**Comment by lanzagar** [comment]
I think a local embedder is something we should have. If this is as fast as we can do it for now, I think it is ok. We still have the option to use the server for faster computations (if it was the same speed, remote embedders would kind of lose sense)...
If tensorflow is unavoidably so much faster than numpy, we can consider (in the future, not in this PR) to have two implementations and use tensorflow when it is available (if user has it installed) otherwise fall back to this numpy implementation.

**Comment by markotoplak** [comment]
I agree with @lanzagar.

**Comment by PrimozGodec** [comment]
@lanzagar I agree too. I will try to speed up local Numpy embedders a bit but it will not be significant. I will also try to test whether we can use PyTorch instead of Tensorflow - it is smaller in size. 

Form my side this PR is ready to merge after it will be checked.

**Comment by markotoplak** [comment]
@PrimozGodec, in the first commit of this PR you added a big file (a model), which you later removed. Could you rebase this file out as it would only increase repository?

I am OK with keeping tensorflow code in history, but I'd be careful about big files.

**Comment by PrimozGodec** [comment]
@markotoplak I removed it. I will also consider rebasing some other commits since some of them does not make sense. 

Currently, I am solving the issue with `Bus error: 10` which occurs while multiplying in convolution. It occurs with Numpy 1.15.* at my machine, and with Numpy 1.15.4 and 1.16.2 at @BlazZupan's MacOs.

**Comment by PrimozGodec** [comment]
@markotoplak It looks so weird. It has different behavior on different machines. It seems that it is an issue caused by different combinations of imports. I am trying to figure out which combination causes the issue.

**Pull request merged**
