### PR TITLE
Redesign of embedder

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

When using server embedder it took long to chancel the embedding process due to long timeout. The user needed to wait for embedding being chancel up to a minute when no internet connection.

##### Description of changes

To solve the issue described before we redesigned the widget:
- ImageEmbedder is only initialized when image start to process
- Cancel functionality does not wait for ImageEmbedder to finish. It is forced to stop but can stop in the background and then get deleted 
- Since widget does not stay connected to the server any more server connection infobox is removed and input data info are moved to newly introduced  input_summary in the footer
- Some new warnings are introduced
- Added additional tests

##### Testing

One who will test the widget must test it completely since most of the widget vital functionalities were changed. Especially test canceling the embedding during the run and run it again manually, changing the embedder and changing the image attribute. Also, check whether there are always all embeddings at the output.

##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I managed to get one error, but I don't know the exact steps to reproduce it. 🙈

```
-------------------------- AttributeError Exception ---------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 287, in __set_results
    embeddings = f.result()
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 239, in run_embedding
    file_paths=paths, image_processed_callback=advance)
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 120, in __call__
    return self._embedder.from_file_paths(*args, **kwargs)
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/server_embedder.py", line 88, in from_file_paths
    b_images, image_processed_callback, repeats_counter
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/server_embedder.py", line 166, in _send_to_server
    body_bytes=image
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/http2_client.py", line 119, in _send_request
    raise ConnectionError(self._no_conn_err)
ConnectionError: No connection with server, call reconnect_to_server()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 292, in __set_results
    self._set_server_info(connected=False)
AttributeError: 'OWImageEmbedding' object has no attribute '_set_server_info'
-------------------------------------------------------------------------------
```

**Comment by ajdapretnar** [comment]
Ok, I can reproduce it is as such:
- use VGG-19 embedder
- deselect Apply automatically
- press Apply
- disconnect the internet
- wait until the error appears

**Comment by thocevar** [comment]
I got exactly the same error with "Inception v3".

**Comment by PrimozGodec** [comment]
@ajdapretnar and @thocevar the error should be fixed now. 

The only thing I do not understand is why como box looks still disabled after calling (it is called when cancel button is clicked):

    self.cb_embedder.setDisabled(False)

they become enabled when I click on them. I think there must be some qt issue. @ales-erjavec do you have any idea?

**Comment by ales-erjavec** [comment]
>  I think there must be some qt issue.

Which PyQt5/Qt version are you using?
On macOS avoid 5.10.*, 5.11.*. Try 5.9.2, 5.12.* or 5.13.*

**Comment by thocevar** [comment]
I found a different problem. If you disconnect the internet connection, you can cancel the embedder. However, if you try to start it again (as might often happen), you have to wait for a minute before it realizes that the connection is still down and lets you do anything else.

**Comment by PrimozGodec** [comment]
@ales-erjavec I am currently using 5.13.*, I also tested with 5.12.* The issue still persist independent of version I use.

**Comment by PrimozGodec** [comment]
@thocevar there was an issue that both processes were accidentally executed in the same thread. Now it should be fixed.

**Comment by ales-erjavec** [comment]
> I am currently using 5.13., I also tested with 5.12. The issue still persist independent of version I use.

It works fine for me. I cannot duplicate the behavior.

**Comment by PrimozGodec** [comment]
@ales-erjavec then it seems it there is a problem of my current configuration. I will try to find out the reason for that, but this issue is not connected with this PR so I thnk this PR can be merged if everything works.

**Comment by ajdapretnar** [comment]
This looks ok to me now.

**Pull request merged**
