### PR TITLE
Image grid lables

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

Implements https://github.com/biolab/orange3-imageanalytics/issues/113

##### Description of changes

Adding labels at the bottom of images in the grid.

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
I also tested it on Windows and it looks ok - same than macOS. @ajdapretnar and @robertcv can you check?

**Comment by robertcv** [comment]
It crashes when changing input data - the labels model doesn't update.

**Comment by PrimozGodec** [comment]
@robertcv it should be fixed now

**Comment by PrimozGodec** [comment]
I fixed the tests so it can be merged if everything is OK @robertcv

**Pull request merged**
