### PR TITLE
[ENH] Embedder users ServerEmbedder component and httpx

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

The script for Server embedder is now in Orange https://github.com/biolab/orange3/pull/4396

##### Description of changes
- Adapting current embedders to the new script. 
- Fixing some bugs
- Code refactoring

This PR should not be merged before Orange 3.25 is released!!

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
I got

```
Traceback (most recent call last):
  File "/Users/janez/miniconda3/envs/o3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/janez/addons/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 71, in run_embedding
    images, col=file_paths_attr, callback=advance
  File "/Users/janez/addons/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 176, in __call__
    self._init_embedder()
  File "/Users/janez/addons/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 141, in _init_embedder
    "image",
  File "/Users/janez/addons/orange3-imageanalytics/orangecontrib/imageanalytics/server_embedder.py", line 16, in __init__
    model_name, max_parallel_requests, server_url, embbedder_type
  File "/Users/janez/orange3/Orange/misc/server_embedder.py", line 64, in __init__
    "error-reporting/machine-id", "", type=str
TypeError: unable to convert a QVariant of type 1024 to a QMetaType of type 10
```

It may be just some misconfiguration on my side.

It works if I change that line from

```python
        self.machine_id = QSettings().value(
            "error-reporting/machine-id", "", type=str
        ) or str(uuid.getnode())
```

to 

```python
self.machine_id = str(uuid.getnode())
```

Note that this line is not in the add-on but in the core Orange's utils.

**Comment by PrimozGodec** [comment]
@janezd it seems to be an extremely rare case. This line is in the embedders for the last two years and was never a problem. Anyway, it seems it can happen, so I made a PR in Orange repository where I catch this error. Hope it is ok solution since I do not understand the reason why it happens

**Comment by AndrejaKovacic** [comment]
Embedders work fine. If it's not too complex for this PR:  after you press cancel, there is no option to resume/restart the calcuation.

**Comment by matjazp** [comment]
> @janezd it seems to be an extremely rare case. This line is in the embedders for the last two years and was never a problem. Anyway, it seems it can happen, so I made a PR in Orange repository where I catch this error. Hope it is ok solution since I do not understand the reason why it happens

heisenbug in action ;)

**Comment by PrimozGodec** [comment]
@AndrejaKovacic It is quite complicated, also the embedding component (in Orange) would need to be changed. It is for sure one of the future tasks but not for this PR.

Actually current embedded is handling reruns quite ok. Since all embeddings are cached locally it takes almost no time to embed already embedded images again. 

Thank you for checking this PR. I will merge it.

**Pull request merged**
