### PR TITLE
[FIX] Image grid selection on the output

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

https://github.com/biolab/orange3-imageanalytics/issues/108
Selectied variable in the output data does not show the selected images correctly

##### Description of changes
Selected variable in output data fixed to mark correct image
`Selected images` set as a default output.
The lowest suported version of Orange incraset to 3.7

##### Includes
- [X] Code changes
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I have tested this and it look good. Not sure why the tests are failing though. Locally, they pass.

**Comment by PrimozGodec** [comment]
@ajdapretnar I think it is ready to merge now

**Comment by PrimozGodec** [comment]
@ajdapretnar if you agree with changes it can be merged

**Comment by ajdapretnar** [comment]
Yes, I was waiting for tests to pass and forgot about it a bit. 🙈

**Pull request merged**
