### PR TITLE
Reimplement image embedding

### PR DESCRIPTION
**Pull request by inejc**
This pull request introduces several changes to the client-side image embedding.

The ImageProfiler (now ImageEmbedder) class is reimplemented and uses http2 protocol to communicate with the backend server (allowing multiple requests and responses to be sent at the same time over a single TCP connection). Additionally, images are sent over the wire in a binary (instead of a textual) format. Unit tests were also written for the ImageEmbedder class.

The OWImageNetEmbedding widget is refactored and changed so that it uses the new functionality. Remote calls regarding server tokens and coins were removed.

Furthermore a new api route naming is proposed (the last commit introduces changes that take the new naming scheme into account for future compatibility when backend service is changed):

- all image related calls (from this addon) should start with `/image` (and e.g. with `/text` from the text addon)

- as discussed with @BlazZupan and @astaric support for other models should be added soon, so `/../model_name` seems appropriate (e.g. `api.biolab.si/image/model_name`)

- when selection of different model layers is introduced the option should be a http POST parameter to the same url

### CODE REVIEW

**Comment by BlazZupan** [comment]
Please change such that "Connected to server" is not shown as a warning but rather as an info in the Info box. Warning should be issued when the widget could not establish connection with a server.

Crashes when processing larger image sets. I have used a set with 823 images and got the following error:

`Error calling 'set_data' of 'ImageNet Embedding'
Traceback (most recent call last):
  File "/Users/blaz/dev/orange3/Orange/canvas/scheme/widgetsscheme.py", line 822, in process_signals_for_widget
    handler(*args)
  File "/Users/blaz/dev/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimagenetembedding.py", line 107, in set_data
    self._cb_image_attr_changed()
  File "/Users/blaz/dev/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimagenetembedding.py", line 116, in _cb_image_attr_changed
    self.commit()
  File "/Users/blaz/dev/orange3/Orange/widgets/gui.py", line 1972, in unconditional_commit
    do_commit()
  File "/Users/blaz/dev/orange3/Orange/widgets/gui.py", line 1980, in do_commit
    commit()
  File "/Users/blaz/dev/orange3-imageanalytics/orangecontrib/imageanalytics/widgets/owimagenetembedding.py", line 132, in commit
    image_processed_callback=lambda: progress.advance()
  File "/Users/blaz/dev/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 122, in __call__
    body_bytes=image
  File "/Users/blaz/dev/orange3-imageanalytics/orangecontrib/imageanalytics/image_embedder.py", line 197, in _send_request
    headers=headers
  File "/Users/blaz/.virtualenvs/orange/lib/python3.5/site-packages/hyper/http20/connection.py", line 281, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "/Users/blaz/.virtualenvs/orange/lib/python3.5/site-packages/hyper/http20/connection.py", line 555, in endheaders
    stream.send_headers(headers_only)
  File "/Users/blaz/.virtualenvs/orange/lib/python3.5/site-packages/hyper/http20/stream.py", line 98, in send_headers
    conn.send_headers(self.stream_id, headers, end_stream)
  File "/Users/blaz/.virtualenvs/orange/lib/python3.5/site-packages/h2/connection.py", line 795, in send_headers
    (max_open_streams, self.open_outbound_streams)
h2.exceptions.TooManyStreamsError: Max outbound streams is 128, 128 open`

**Comment by BlazZupan** [comment]
When bigger image sets are processed there is a rather long wait time before anything happens (progress bar does not start running). Probably not everything should be transferred to the server right away, but rather in smaller chunks.

**Comment by matjazp** [comment]
send_headers (max_open_streams, self.open_outbound_streams) h2.exceptions.TooManyStreamsError: Max outbound streams is 128, 128 open

This is probably the limit set on the Nginx side (on the server). Nginx has a default parameter MAX_CONCURRENT_STREAMS=128 (https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_concurrent_streams).

**Comment by inejc** [comment]
As discussed with @matjazp I have added the batch sending functionality. Images are now sent in multiple batches and the batch size parameter is controlled by the remote server (the client adapts to it when establishing a connection).

There is still one issue on the backend side (see. the referenced pull request)

**Pull request merged**
